spring:
  application:
    name: spring-cloud-eureka
    
server:
  port: 8001
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:peer1:8001/eureka/
  instance:
    hostname: peer2 